name: diccon_evo
description: A new Diccon that work on many platforms.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.1+62

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # This lib to set windows size on Windows.
  window_manager: ^0.3.6
  # Provide ability to speak a provided word.
  flutter_tts: ^3.8.3
  http: ^1.1.0
  # A Flutter plugin for finding commonly used locations on the filesystem
  path_provider: ^2.1.1
  audioplayers: ^5.2.0
  # Package for Packaging Windows App
  msix: ^3.16.6
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1
  # Save settings
  shared_preferences: ^2.2.1
  # This package help us create a notification in the bottom app
  fluttertoast: ^8.2.2
  # State management combination
  flutter_bloc: ^8.1.3

  # Help us loaf svg image
  flutter_svg: ^2.0.9
  # Open link
  url_launcher: ^6.2.1
  # using firebase_core: ^2.10.0 get windows build without error
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  firebase_storage: ^11.5.0
  cloud_firestore: ^4.13.0
  firebase_app_check: ^0.2.1+4
  google_sign_in: ^6.1.6

  # custom icon
  font_awesome_flutter: ^10.6.0
  unicons: ^2.1.1
  # localization
  i18n_extension: ^9.0.2
  flutter_localization: ^0.1.14
  # gpt
  chat_gpt_flutter: ^1.0.15
  # use to check internet connectivity
  internet_connection_checker: ^1.0.0+1
  # create dotted indicator for pageview
  smooth_page_indicator: ^1.1.0
  # create route for application
  go_router: ^12.0.1
  collection: ^1.17.0
  flutter_localizations:
    sdk: flutter
  # use for customizing theme
  dynamic_color: ^1.6.8
  #wave animation
  wave: ^0.2.2
  speech_to_text: ^6.4.0
  loading_indicator: ^3.1.1
  sqflite: ^2.3.0
  # sql for windows
  sqlite3_flutter_libs: ^0.5.18
  sqflite_common_ffi: ^2.3.0+3
  # The path package provides common operations for manipulating paths: joining, splitting, normalizing, etc
  path: ^1.8.3
  # i use this to create hash value for question asnwer
  crypto: ^3.0.3
  # combo to translate image
  camera: ^0.10.5+5
  # text recognition
  google_mlkit_text_recognition: ^0.10.0
  # detect language
  google_mlkit_language_id: ^0.9.0
  image_picker: ^1.0.4
  translator:
    git:
      url: https://github.com/tranhuudang/google-translator
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  expandable_page_view: ^1.0.17
  wave_divider: ^0.0.2
  wavy_slider: ^0.0.3
  # this package help me create a somple way to add search view in searching stories
  search_page: ^2.3.0
  metaballs: ^1.5.0
  # handle external varialble - key
  envied: ^0.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  envied_generator: ^0.5.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/dictionary/
    - assets/thesaurus/english_synonyms.json
    - assets/thesaurus/english_antonyms.json
    - assets/badges/
    - assets/essential/
    - assets/stories/
    - assets/theme/
    - assets/conversation_support/
    - assets/illustrations/
    - assets/fonts/
msix_config:
  display_name: Diccon Evo
  publisher_display_name: Zeroboy
  identity_name: 24555Zeroboy.DicconEvo
  publisher: CN=DA7D2C99-987C-4B69-8953-17157F6E0E1A
  msix_version: 1.4.3.0
  logo_path: C:\Users\Zr\StudioProjects\diccon_evo\assets\icon.ico
  store: true
